services:
  api:
    image: node:23.14.0
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    working_dir: /app
    command: npm run dev
    depends_on:
      - db
  db:
    image: postgress
    environment:
      - POSTGRES_PASSWORD: postgres
      - POSTGRES_USER: postgres
      - POSTGRES_DB: app
    volumes:
      - db-data:/var/lib/postgresql/data
  volumes:
    db-data:
